# The URL the site will be built for
base_url = "https://CSUwangj.github.io/ZDaily/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true


# search is not available by now
build_search_index = false
generate_feed = true
feed_filename = "rss.xml"
taxonomies = [
  {name = "categories", rss = true},
  {name = "tags", rss = true},
  {name = "archives", rss = true},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "monokai"


[extra]
# nav menu title
site_name = "DogFood"
menu_items = [
  {url = "$BASE_URL", name = "Home", icon = "fa-solid fa-house"},
  {url = "$BASE_URL/about", name = "About", icon = "fa-solid fa-user-circle"},
  {url = "$BASE_URL/categories", name = "Categories", icon = "fa-solid fa-book"},
  {url = "$BASE_URL/tags", name = "Tags", icon = "fa-solid fa-tags"},
  {url = "$BASE_URL/archives", name = "Archives", icon = "fa-solid fa-inbox"},
]
# will be used everywhere ;D
author = "CSUwangj"
# will be used in about page and sidebar
quote = "Just keep in mind that hacking is very rarely in a sequence."
links = [
  {name = "Author of DogFood", url = "https://CSUwangj.github.io/"},
]
# check font awesome 6 for more favicon
author_links = [
  {name = "Github", url = "https://github.com/CSUwangj", favicon = "fa-brands fa-github"},
]
copyright_year = "2018-2022"
# will be in about page and side bar
avatar = "img/avatar.png"
# used for $$$$ quoted math formula
katex_enabled = true
# "left" or "right" or "none"
sidebar = "left"
