name = "DogFood"
description = "A blog theme"
license = "MIT"
homepage = "https://github.com/CSUwangj/DogFood"
# The minimum version of Zola required
min_version = "0.4.0"
# An optional live demo URL
demo = ""

# Any variable there can be overriden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

# The theme author info: you!
[author]
name = "CSUwangj"
homepage = "https://CSUwangj.github.io"
